version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/steambay
      - ENVIRONMENT=docker
      - ALLOWED_ORIGINS=http://localhost:3000
      - SESSION_SECRET=development_session_secret
      - REACT_APP_API_URL=http://localhost:8000
      - NODE_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=steambay
      - PYTHONPATH=/app/src
    ports:
      - "8000:8000"  # Backend API
      - "3000:3000"  # Frontend
    command: >
      bash -c "
        echo 'Starting PostgreSQL...' &&
        service postgresql start &&
        echo 'Waiting for PostgreSQL...' &&
        sleep 5 &&
        echo 'Initializing database...' &&
        cd /app &&
        python -m src.init_db &&
        echo 'Database initialized' &&
        cd frontend && npm install &&
        echo 'Frontend dependencies installed' &&
        (npm start &) &&
        echo 'Frontend started' &&
        cd .. &&
        uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
      " 